function [fitresult, gof] = createFit(theta, Sin3)
%CREATEFIT(THETA,SIN3)
%  Create a fit.
%
%  Data for 'Fit with Sum of Sine' fit:
%      X Input : theta
%      Y Output: Sin3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-May-2017 08:40:48


%% Fit: 'Fit with Sum of Sine'.
[xData, yData] = prepareCurveData( theta, Sin3 );

% Set up fittype and options.
ft = fittype( 'sin5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.Normalize = 'on';
opts.StartPoint = [8.56778232146417 0.929541452128413 1.58994537196886 3.58823783849408 1.85908290425683 -1.52872258378883 0.741051282508951 3.71816580851365 1.6530306331943 0.790063188862965 5.57724871277048 -2.74026542588515 0.726974506069899 11.154497425541 0.103221241060839];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit with Sum of Sine' );
h = plot( fitresult, xData, yData );
legend( h, 'Sin3 vs. theta', 'Fit with Sum of Sine', 'Location', 'NorthEast' );
% Label axes
xlabel theta
ylabel Sin3
grid off


